<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="C_galut.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Prekės" Member="Prekės">
    <Type Name="Prekės">
      <Column Name="Prekės_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prekės_pavadinimas" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Prekės_kaina" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Kiekis_sandelyje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>