#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_galut
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPrekės(Prekės instance);
    partial void UpdatePrekės(Prekės instance);
    partial void DeletePrekės(Prekės instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::C_galut.Properties.Settings.Default.Database1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Prekės> Prekės
		{
			get
			{
				return this.GetTable<Prekės>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prekės")]
	public partial class Prekės : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Prekės_Id;
		
		private string _Prekės_pavadinimas;
		
		private double _Prekės_kaina;
		
		private int _Kiekis_sandelyje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrekės_IdChanging(int value);
    partial void OnPrekės_IdChanged();
    partial void OnPrekės_pavadinimasChanging(string value);
    partial void OnPrekės_pavadinimasChanged();
    partial void OnPrekės_kainaChanging(double value);
    partial void OnPrekės_kainaChanged();
    partial void OnKiekis_sandelyjeChanging(int value);
    partial void OnKiekis_sandelyjeChanged();
    #endregion
		
		public Prekės()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prekės_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Prekės_Id
		{
			get
			{
				return this._Prekės_Id;
			}
			set
			{
				if ((this._Prekės_Id != value))
				{
					this.OnPrekės_IdChanging(value);
					this.SendPropertyChanging();
					this._Prekės_Id = value;
					this.SendPropertyChanged("Prekės_Id");
					this.OnPrekės_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prekės_pavadinimas", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Prekės_pavadinimas
		{
			get
			{
				return this._Prekės_pavadinimas;
			}
			set
			{
				if ((this._Prekės_pavadinimas != value))
				{
					this.OnPrekės_pavadinimasChanging(value);
					this.SendPropertyChanging();
					this._Prekės_pavadinimas = value;
					this.SendPropertyChanged("Prekės_pavadinimas");
					this.OnPrekės_pavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prekės_kaina", DbType="Float NOT NULL")]
		public double Prekės_kaina
		{
			get
			{
				return this._Prekės_kaina;
			}
			set
			{
				if ((this._Prekės_kaina != value))
				{
					this.OnPrekės_kainaChanging(value);
					this.SendPropertyChanging();
					this._Prekės_kaina = value;
					this.SendPropertyChanged("Prekės_kaina");
					this.OnPrekės_kainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kiekis_sandelyje", DbType="Int NOT NULL")]
		public int Kiekis_sandelyje
		{
			get
			{
				return this._Kiekis_sandelyje;
			}
			set
			{
				if ((this._Kiekis_sandelyje != value))
				{
					this.OnKiekis_sandelyjeChanging(value);
					this.SendPropertyChanging();
					this._Kiekis_sandelyje = value;
					this.SendPropertyChanged("Kiekis_sandelyje");
					this.OnKiekis_sandelyjeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
